run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
    - misspell
    - gocyclo
    - gosec
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
